version: '2.2'
services:
  web:
    container_name: ${PROJECT_NAME}_web
    image: ${PROJECT_NAME}_web:${RELEASE_VERSION}
    build:
      context: build/web
      dockerfile: Dockerfile
      args:
        - FLASK_PORT=${FLASK_PORT:-5000}
    environment:
      - FLASK_PORT=${FLASK_PORT:-5000}
    volumes:
      - ./src:/home/app/src
    ports:
      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"